---
deployment:
  tasks:
    - export DRUPALPATH=/home/motocomp/public_html/admin/
    - cp ~/repositories/moto-comparo/drupal/composer.lock ${DRUPALPATH}
    - cp -r ~/repositories/moto-comparo/drupal/patches ${DRUPALPATH}
    - cd ${DRUPALPATH}
    - /opt/cpanel/composer/bin/composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
    - drush deploy -v -y
