---
deployment:
  tasks:
    - export DEPLOYPATH=/home/motocomp/public_html/
    - /opt/cpanel/composer/bin/composer install --prefer-dist --no-progress --no-suggest
    - /bin/cp -R * $DEPLOYPATH
#    - vendor/bin/drush config:import --yes
#    - vendor/bin/drush updatedb
#    - vendor/bin/drush cache:rebuild
    - pwd
    - echo $PATH
    - /home/motocomp/vendor/drush/drush/drush deploy -v -y
