initial_image_styles:
  large: large
  max_1300x1300: max_1300x1300
  max_2600x2600: max_2600x2600
  max_325x325: max_325x325
  max_650x650: max_650x650
  media_library: media_library
  medium: medium
  slick_media: slick_media
  thumbnail: thumbnail
queue_image_styles: {  }
